# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Antoine Toulme
title: Developer
email: antoine@toulme.name
website: www.github.com/atoulme/resume

# Social links
twitter_username: _tmio
github_username:  atoulme
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: toulmean
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a leader with a strong track record of delivering consistent, ROI driven business value. 
  I produce powerful software architectures, from requirements to production. 
  I enjoy managing large agile multinational teams.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  I live in Silicon Valley, California, where life is sweet and kids grow happy.
  Besides software engineering, I play board games, dabble in 3d printing and organize excursions for my cub scout.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
